apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-ns # will need to use the -n my-ns flag in order to get/describe this pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
      ports:
        - containerPort: 80 # used to expose this container to outside of pod 
      resources:
        requests:
          memory: "64Mi" # 64 megabytes
          cpu: "250m" # 250 milli cpus. a millicpu is 1/1000 of a cpu core i.e this is 25% of a cpu core
        limits:
          memory: "128Mi" # container will be killed if this is exceeded
          cpu: "500m" # kill if container uses more than half a cpu core
  securityContext:
      env:
        - name: MY_PASSWORD # create new environment variable visible to the container
          valueFrom: # where to retrieve value for new environment var
            secretKeyRef: # look for value in specific key of a secret
              name: my-secret # name of secret
              key: myKey # name of key within that secret
    runAsUser: 2001 # restrict to priviledges of this user
    fsGroup: 3001 # restrict to priviledges of this group